
# Curso de Métodos Numéricos

### Práctica 3: Normas vectoriales, normas matriciales y número de condición


Importar NumPy

Por convención, NumPy se importa utilizando el alias `np`.


In [7]:
import numpy as np


## Normas de vectores

Sea

$$
x=(x_1,\ldots,x_n).
$$

### Norma 1

$$
\|x\|_1=\sum_{i=1}^n |x_i|.
$$

### Norma 2 o norma euclidiana

$$
\|x\|_2=
\left(\sum_{i=1}^n |x_i|^2\right)^{1/2}.
$$

### Norma infinito

$$
\|x\|_\infty=\max_i |x_i|.
$$

en Python dichas normas se pueden calcular como se indica en el siguiente bloque de código.

In [8]:

x = np.array([1, 0, 3, -2])

norma_1 = np.linalg.norm(x, ord=1)
norma_2 = np.linalg.norm(x, ord=2)
norma_inf = np.linalg.norm(x, ord=np.inf)

print("x =", x)
print("Norma 1:", norma_1)
print("Norma 2:", norma_2)
print("Norma infinito:", norma_inf)


x = [ 1  0  3 -2]
Norma 1: 6.0
Norma 2: 3.7416573867739413
Norma infinito: 3.0



Podemos calcular las normas de forma manual de la siguiente manera:


In [9]:
x = np.array([1, 0, 3, -2])

norma_1_manual = np.sum(np.abs(x))
norma_2_manual = np.sqrt(np.sum(x**2))
norma_inf_manual = np.max(np.abs(x))

print("Norma 1 calculada manualmente:", norma_1_manual)
print("Norma 2 calculada manualmente:", norma_2_manual)
print("Norma infinito calculada manualmente:", norma_inf_manual)


Norma 1 calculada manualmente: 6
Norma 2 calculada manualmente: 3.7416573867739413
Norma infinito calculada manualmente: 3



## Normas de matrices

Para una matriz $A=(a_{ij})\in\mathbb{C}^{m\times n}$, algunas normas importantes son las siguientes.

### Norma matricial 1

$$
\|A\|_1 =
\max_{1\leq j\leq n}
\sum_{i=1}^m |a_{ij}|.
$$

Es decir, es la máxima suma absoluta de las columnas.

### Norma matricial infinito

$$
\|A\|_\infty =
\max_{1\leq i\leq m}
\sum_{j=1}^n |a_{ij}|.
$$

Es decir, es la máxima suma absoluta de las filas.

### Norma matricial 2

$$
\|A\|_2 =
\sqrt{\rho(A^T A)}.
$$

Es decir, la raíz cuadrada del radio espectral del producto $A^T A$ (si $A$ es compleja cambiar $A^T$ por $A^*$).

Los mismos comandos que cálculan normas vectoriales pueden utilizarce para cálcular normas matriciales.


In [10]:

A = np.array([
    [1, -2,  0],
    [3,  1, -1]
])

norma_A_1 = np.linalg.norm(A, ord=1)
norma_A_2 = np.linalg.norm(A, ord=2)
norma_A_inf = np.linalg.norm(A, ord=np.inf)

print("A =")
print(A)

print("\nNorma matricial 1:", norma_A_1)
print("Norma matricial 2:", norma_A_2)
print("Norma matricial infinito:", norma_A_inf)


A =
[[ 1 -2  0]
 [ 3  1 -1]]

Norma matricial 1: 4.0
Norma matricial 2: 3.340999500174817
Norma matricial infinito: 5.0



Podemos cálcular las normas 1 e infinito "manualmente" calculando las sumas absolutas de columnas y filas.


In [11]:

sumas_columnas = np.sum(np.abs(A), axis=0) # suma cada columna y guarda el resultado en un vector
sumas_filas = np.sum(np.abs(A), axis=1) # suma cada fila y guarda el resultado en un vector

print("Sumas absolutas por columna:", sumas_columnas)
print("Máxima suma por columna:", np.max(sumas_columnas))

print("\nSumas absolutas por fila:", sumas_filas)
print("Máxima suma por fila:", np.max(sumas_filas))


Sumas absolutas por columna: [4 3 1]
Máxima suma por columna: 4

Sumas absolutas por fila: [3 5]
Máxima suma por fila: 5



##  Norma de Frobenius

La norma de Frobenius de una matriz es

$$
\|A\|_F =
\left(
\sum_{i=1}^m\sum_{j=1}^n |a_{ij}|^2
\right)^{1/2}.
$$

Puede interpretarse como la norma euclidiana del vector formado por todas las entradas de la matriz.

Se cálcula de la siguiente manera.


In [12]:

A = np.array([
    [1, -2, 0],
    [3,  1, 4]
])

norma_F = np.linalg.norm(A, ord="fro")

print("A =")
print(A)
print("\nNorma de Frobenius:", norma_F)


A =
[[ 1 -2  0]
 [ 3  1  4]]

Norma de Frobenius: 5.5677643628300215


La norma de Frobenius se puede calcular manualmente de la siguiente forma:

In [13]:

norma_F_manual = np.sqrt(np.sum(A**2))

print("Norma de Frobenius calculada manualmente:", norma_F_manual)


Norma de Frobenius calculada manualmente: 5.5677643628300215


## Resumen de comandos

| Operación | Comando |
|---|---|
| Crear un vector | `np.array([1, 2, 3])` |
| Crear una matriz | `np.array([[1, 2], [3, 4]])` |
| Norma vectorial 1 | `np.linalg.norm(x, ord=1)` |
| Norma vectorial 2 | `np.linalg.norm(x, ord=2)` |
| Norma vectorial infinito | `np.linalg.norm(x, ord=np.inf)` |
| Norma matricial 1 | `np.linalg.norm(A, ord=1)` |
| Norma matricial 2 | `np.linalg.norm(A, ord=2)` |
| Norma matricial infinito | `np.linalg.norm(A, ord=np.inf)` |
| Norma de Frobenius | `np.linalg.norm(A, ord="fro")` |
| Número de condición en norma 1 | `np.linalg.cond(A, p=1)`|
| Número de condición en norma infinito | `np.linalg.cond(A, p=np.inf)`|
| Número de condición en norma de Frobenius | `np.linalg.cond(A, p="fro")`|


## Práctica del curso

### Ejercicio 1

Escribir una función que calcule la norma uno, de una matriz dada, sin usar ninguna funcion de Numpy excepto "A.shape".

Comparar los resultados obtenidos con la norma uno calculada por Numpy para la matriz:

```python
A = np.array([
    [1, -2, 0],
    [3, 1, 4]
])
```

In [14]:
# Escriba aquí su solución

### Ejercicio 2

Escribir una función que calcule la norma infinito, de una matriz dada, sin usar ninguna funcion de Numpy excepto "A.shape".

Comparar los resultados obtenidos con la norma infinito calculada por Numpy para una
matriz aleatoria de 4 por 4.

In [15]:
# Escriba aquí su solución

### Ejercicio 3

Escribir una función que calcule la norma de Frobenius, de una matriz dada, sin usar ninguna funcion de Numpy excepto "A.shape".

Comparar los resultados obtenidos con la norma de Frobenius calculada por Numpy para una 
matriz aleatoria de 4 por 4.

In [16]:
# Escriba aquí su solución

### Ejercicio 4. Matrices de Hilbert

La matriz de Hilbert de orden $n$ se define mediante

$$
(H_n)_{ij}=\frac{1}{i+j-1},
\qquad i,j=1,\ldots,n.
$$

Por ejemplo,

$$
H_3=
\begin{pmatrix}
1 & \frac12 & \frac13\\[0.3cm]
\frac12 & \frac13 & \frac14\\[0.3cm]
\frac13 & \frac14 & \frac15
\end{pmatrix}.
$$

Las matrices de Hilbert son ejemplos clásicos de matrices **muy mal condicionadas**. 
### Actividades:

1. Implemente una función `matriz_hilbert(n)` que construya $H_n$.
2. Para $n=1,\ldots,10$, calcule $cond_2(H_n)$ (usando NumPy).
3. Represente gráficamente el número de condición en función de $n$.

In [17]:
###

### Ejercicio 5. Matrices de Vandermonde

Dados cuatro escalares $x_0,x_1,x_2,x_3$, se define la matriz de Vandermonde (de 4 por 4) como

$$
V=
\begin{pmatrix}
1 & x_0 & x_0^2 & x_0^3\\[0.3cm]
1 & x_1 & x_1^2 & x_1^3\\[0.3cm]
1 & x_2 & x_2^2 & x_2^3\\[0.3cm]
1 & x_3 & x_3^2 & x_3^3
\end{pmatrix}.
$$


#### Actividades

1. Defina una función que construya una matriz de Vandermorde de 4 por 4.
2. Calcular el número de condición en norma $2$ para la matriz de Vandermorde con entradas $(x_0,x_1,x_2,x_3)=(1,2,3,4)$ (el valor de dicho número de
condición debería ser mayor a $1000$).

In [ ]:
###

